export const FETCH_SONGS ='FETCH_SONGS';
export const FETCH_SONGS_SUCCESS ='FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_FALIURE ='FETCH_SONGS_FALIURE';
export const SEARCH ='SEARCH';
export const SEARCH_SUCCESS ='SEARCH_SUCCESS';
export const SEARCH_FALIURE ='SEARCH_FALIURE';
