export const FETCH_SONG_TO_PLAY = 'FETCH_SONG_TO_PLAY';
export const FETCH_SONG_TO_PLAY_SUCCESS = 'FETCH_SONG_TO_PLAY_SUCCESS';
export const FETCH_SONG_TO_PLAY_FALIURE = 'FETCH_SONG_TO_PLAY_FALIURE';
export const UPLOAD_SONG = 'UPLLOAD_SONG';
export const UPLOAD_SONG_SUCCESS = 'UPLOAD_SONG_SUCCESS';
export const UPLOAD_SONG_FAILURE = 'UPLOAD_SONG_FAILURE';

